# Generated by Django 3.2.7 on 2021-10-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resister',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='resister',
            name='last_name',
        ),
    ]
